version: '3.3'

services:
  gateway:
    hostname: 'gateway'
    build:
      context: .
      args:
        GATEWAY_SERVER: ${GATEWAY_SERVER:-miner}
        GATEWAY_TYPE: ${GATEWAY_TYPE:-sx1250}
        GATEWAY_REGION: ${GATEWAY_REGION:-US915}
    restart: always
    privileged: true
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
    network_mode: "service:miner"
    volumes:
      - /sys:/sys
      - /dev:/dev

  miner:
    hostname: 'miner'
    image: quay.io/team-helium/miner:${MINER_TAG:-latest-arm64}
    restart: always
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
    ports:
      - "44158:44158/tcp"
      - "1680:1680/udp"
    volumes:
      - ${MINER_VOLUME:-/var/data}:/var/data

    environment:
      - REGION_OVERRIDE=${GATEWAY_REGION:-US915}
